idf_component_register(
    SRCS
        "app_main.c"
        "../components/sensors/hardware_i2c_sensor.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        "ui"
        "bluetooth"
        "sensors"
        "network"
        "services"
        "drivers"
        "nvs_flash"
        "bt"
        "esp_timer"
        "espressif__esp_lvgl_port"
)
