idf_component_register(
    SRCS
        "ui.c"
        "ui_alarm.c"
        "ui_apps.c"
        "ui_connect.c"
        "ui_health.c"
        "ui_icons.c"
        "ui_menu.c"
        "ui_navigation.c"
        "ui_notification_popup.c"
        "ui_shutdown_dialog.c"
        "ui_stopwatch.c"
        "ui_update.c"
        "ui_utils.c"
        "ui_watchface.c"
        "ui_wifi.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        "drivers"
        "bluetooth"
        "sensors"
        "network"
        "services"
        "assets"
        "lvgl__lvgl"
        "espressif__esp_lvgl_port"
        "espressif__esp_lcd_touch_cst816s"
        "jbrilha__esp_lcd_st7789"
        "bt"
        "nvs_flash"
        "driver"
        "esp_timer"
        "esp_wifi"
        "esp_netif"
)
